spring:
  application:
    name: api-terminals
  cloud:
    config:
      import-check:
        enabled: false
  data:
    mongodb:
      uri: ${MONGO_URL}
      auto-index-creation: true
      uuid-representation: standard
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

springdoc:
  api-docs:
    path: ${APP_PATH}/swagger-ui/api-docs
  swagger-ui:
    path: ${APP_PATH}/index.html

acquirers:
  operable:
    - id: "GPS"
    - id: "BANORTE"
