spring:
  application:
    name: api-seeds
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
springdoc:
  api-docs:
    path: ${APP_PATH}/swagger-ui/api-docs
  swagger-ui:
    path: ${APP_PATH}/index.html

libs:
  security:
    ignore-paths: ["/actuator/**"]
    resource-server:
      issuers:
        - name: "merchant"
          uri: "https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_AWS_MERCHANT_POOL}"
          authorities-claim-key: "cognito:groups"
        - name: "customer"
          uri: "https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_AWS_CUSTOMER_POOL}"
          authorities-claim-key: "cognito:groups"
        - name: "support"
          uri: "https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_AWS_SUPPORT_POOL}"
          authorities-claim-key: "cognito:groups"
    requester-user:
      provider:
        enabled: true
    ownership:
      enabled: false

elastic:
  apm:
    enabled: true
    server-url: ${ELASTIC_CLOUD_URL}
    service-name: ${ELASTIC_CLOUD_TAG_APP}
    secret-token: ${ELASTIC_CLOUD_TOKEN}
    environment: ${ELASTIC_CLOUD_TAG_ENV}
    application-packages: com.menta.api.seeds
    log-level: ERROR