spring.application.name: api-banorte-adapter

spring:
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

springdoc:
  api-docs:
    path: ${APP_PATH}/swagger-ui/api-docs
  swagger-ui:
    path: ${APP_PATH}/index.html

api-banorte-adapter:
  url: "http://mock.tools.menta.global/InterredesSeguro"
  timeout: 25500
  execution-mode: "AUT"
  temporal-properties:
    aggregator:
      id: "12"
      child_commerce:
        id: "666"

externals:
  host: "api-internal.dev.apps.menta.global"
  scheme: "https://"
  entities:
    acquirer:
      banorte-merchant:
        url: "${externals.scheme}${externals.host}${externals.entities.acquirer.banorte-merchant.path}"
        path: "/banorte-entities/merchants"
        request-timeout: 5000

elastic:
  apm:
    enabled: true
    server-url: ${ELASTIC_CLOUD_URL}
    service-name: ${ELASTIC_CLOUD_TAG_APP}
    secret-token: ${ELASTIC_CLOUD_TOKEN}
    environment: ${ELASTIC_CLOUD_TAG_ENV}
    application-packages: com.menta.api.banorte
    log-level: ERROR
