spring:
  application:
    name: api-users-authorities
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    listener:
      ack-mode: "manual_immediate"
      missing-topics-fatal: false
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    cloud:
      config:
        import-check:
          enabled: false

springdoc:
  api-docs:
    path: ${APP_PATH}/swagger-ui/api-docs
  swagger-ui:
    path: ${APP_PATH}/index.html

externals:
  host:
    internal: "api-internal.dev.apps.menta.global"
    external: "api.dev.apps.menta.global"
  scheme: "https://"
  entities:
    users:
      url: "${externals.scheme}${externals.host.internal}${externals.entities.users.path}"
      request-timeout: 2500
      path: "/users"

config:
  provider:
    authorities:
      - type: MERCHANT
        authorities: Annulment::Create,AnnulmentReversal::Create,Payment::Create,PaymentReversal::Create,Refund::Create,RefundReversal::Create,Transaction::Read
      - type: CUSTOMER
        authorities: Transaction::Read
      - type: SUPPORT
        authorities: Transaction::Read

event:
  topic:
    user:
      created: created.user
    authority:
      created: created.authority
  group:
    user-authority:
      distribute: user.distribute.authority
      assign: user.assign.authority

elastic:
  apm:
    enabled: true
    server-url: ${ELASTIC_CLOUD_URL}
    service-name: ${ELASTIC_CLOUD_TAG_APP}
    secret-token: ${ELASTIC_CLOUD_TOKEN}
    environment: ${ELASTIC_CLOUD_TAG_ENV}
    application-packages: com.menta.api.users.authorities
    log-level: ERROR