spring.application.name: api-secrets

spring:
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false



#secrets_GPS: 123-123
#ksn_GPS: 123-123
#secrets_BANORTE_444: 1234-123
#secrets_BANORTE_445: 444-444
#secrets_BANORTE_445_33: 111-111
#secrets_BANORTE_445_33_1: 22-222
#secrets_BANORTE_445_35_1: 22-222
event:
  topic:
    terminal:
      secrets:
        updated: updated.terminal.secrets

config:
  acquirers:
    - name: "GPS"
      country:
        - "ARG"
    - name: "FEENICIA"
      country:
        - "MEX"
externals:
  host: "api-internal.dev.apps.menta.global"
  scheme: "https"
  entities:
    terminals:
      path: "/terminals"
      timeout: 10000
    customers:
      path: "/customers"
      timeout: 10000

elastic:
  apm:
    enabled: true
    server-url: ${ELASTIC_CLOUD_URL}
    service-name: ${ELASTIC_CLOUD_TAG_APP}
    secret-token: ${ELASTIC_CLOUD_TOKEN}
    environment: ${ELASTIC_CLOUD_TAG_ENV}
    application-packages: com.menta.apisecrets
    log-level: ERROR
