spring.application.name: api-acquirers

spring:
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false

config:
  acquirers:
    - name: "GPS"
      country: "ARG"
    - name: "FEENICIA"
      country: "MEX"
    - name: "CREDIBANCO"
      country: "CO"

externals:
  host: "api-internal.dev.apps.menta.global"
  scheme: "https"
  entities:
    domain:
      customers:
        url: "${externals.scheme}://${externals.host}${externals.entities.domain.customers.path}"
        request-timeout: 2500
        path: "/customers"
    operations:
      - name: "payments"
        path: "/payments"
      - name: "refunds"
        path: "/refunds"
      - name: "annulments"
        path: "/annulments"
      - name: "reversal_payments"
        path: "/reversals/payments"
      - name: "reversal_refunds"
        path: "/reversals/refunds"
      - name: "reversal_annulments"
        path: "/reversals/annulments"
    acquirers:
      - name: "GPS"
        path: "/gps"
      - name: "FEENICIA"
        path: "/feenicia"
      - name: "CREDIBANCO"
        path: "/credibanco"

libs:
  security:
    ignore-paths: "/private/**, /actuator/**"
    resource-server:
      issuers:
        - name: "merchant"
          uri: "https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_AWS_MERCHANT_POOL}"
          authorities-claim-key: "cognito:groups"
        - name: "customers"
          uri: "https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_AWS_CUSTOMER_POOL}"
          authorities-claim-key: "cognito:groups"

elastic:
  apm:
    enabled: true
    server-url: ${ELASTIC_CLOUD_URL}
    service-name: ${ELASTIC_CLOUD_TAG_APP}
    secret-token: ${ELASTIC_CLOUD_TOKEN}
    environment: ${ELASTIC_CLOUD_TAG_ENV}
    application-packages: com.menta.apiacquirers
    log-level: ERROR