spring.application.name: ms-api-reimbursements

spring:
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
