spring:
  application:
    name: api-credibanco-adapter
  profiles:
    active: default
  cloud:
    config:
      import-check:
        enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    deserialization:
      ADJUST_DATES_TO_CONTEXT_TIME_ZONE: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    listener:
      ack-mode: "manual_immediate"
      missing-topics-fatal: false
    consumer:
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    host: ${REDIS_HOST}
    timeout: 60000
  datasource:
    url: jdbc:mariadb://${MYSQL_HOST}:3306/${MYSQL_DB}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/liquibase-changelog.yml
    enabled: true

springdoc:
  api-docs:
    path: ${APP_PATH}/swagger-ui/api-docs
  swagger-ui:
    path: ${APP_PATH}/index.html

event:
  topic:
    terminal:
      secrets:
        updated: updated.terminal.secrets
    pin:
      key:
        updated: updated.pin.key
  group:
    terminal:
      secrets:
        updated: updated.terminal.secrets
    pin:
      key:
        updated: updated.pin.key

elastic:
  apm:
    enabled: false
    server-url: ${ELASTIC_CLOUD_URL}
    service-name: ${ELASTIC_CLOUD_TAG_APP}
    secret-token: ${ELASTIC_CLOUD_TOKEN}
    environment: ${ELASTIC_CLOUD_TAG_ENV}
    application-packages: com.menta.api.credibanco
    log-level: ERROR

api-credibanco-adapter:
  global:
    constants:
      audit-number: "005069"
      network-international-identifier: "012"
      point-of-service-condition-code: "00"
      terminal-owner-fiid: "0090"
      terminal-logical-network: ${TERMINAL_LOGICAL_NETWORK:CER2} #PRO2 PRODUCCION
      terminal-time-offset: "+000"
      terminal-id: "0000"
      close-transaction-hour: "23"
      info-text: "         "
      acquiring-institution-identification-code: "          "
    settlement-data:
      service: "  "
      originator: "B24 "
      destination: "B24 "
      draft-capture-flag: "1"
      settlement-flag: " "
    card-type:
      card-issuer-fiid: "    "
      logical-network: ${TERMINAL_LOGICAL_NETWORK:CER2}
      category: "0"
      save-account-indicator: "00"
      interchange-response-code: "00000000"
  adapter:
    out:
      request-timeout: "25000"

externals:
  host: "api-internal.dev.apps.menta.global"
  scheme: "https://"
  entities:
    credibanco:
      merchant:
        path: "/credibanco-entities/merchants/{merchantId}"
        url: "${externals.scheme}${externals.host}${externals.entities.credibanco.merchant.path}"
        request-timeout: 5000
      terminal:
        path: "/credibanco-entities/terminals/{terminalId}"
        url: "${externals.scheme}${externals.host}${externals.entities.credibanco.terminal.path}"
        request-timeout: 5000
